require: rubocop-rspec
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'spec/dummy/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'vendor/bundle/**/*'
Metrics/AbcSize:
  Enabled: true
  Max: 16
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'
Metrics/ClassLength:
  Enabled: true
Metrics/CyclomaticComplexity:
  Enabled: true
Metrics/LineLength:
  Enabled: true
  Max: 120
Metrics/MethodLength:
  Enabled: true
Naming/PredicateName:
  Enabled: false
Rails:
  Enabled: true
Rails/ActionFilter:
  Enabled: false
Rails/HttpPositionalArguments:
  Enabled: false
Rails/SkipsModelValidations:
  Exclude:
    - 'db/migrate/**/*.rb'
RSpec/ExampleLength:
  Max: 10
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
